#!/bin/bash
set -e  # Exit immediately if a command exits with a non-zero status.

current_script=$(realpath "$BASH_SOURCE")
base_directory=$(realpath $(dirname "${current_script}")/..)

source $base_directory/tools/utils
build_container_if_needed $current_script vinsmono-docker \
  $base_directory/Dockerfile.app \
  $base_directory/.container.stamp.app \
  $base_directory/catkin/install
